### ISSUE TITLE
Frontend Abwesenheit selbst online eintragen

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#102]
### Beschreibung

Es sollte eine eigene Seite geben auf der Schüler sich krankmelden können, anstatt bei der Schule anzurufen. Dabei sollen sie die Dauer und den Grund eintragen können.

**Optional:**
- Oder statt einer eigenen Seite nur ein kleiner Bereich / Button auf einer anderen Seite

### Task
- [ ] Schüler kann sich Krankmelden 
- [ ] Schüler kann die Dauer und den Grund festlegen (Krankheit, Persönlich oder Sportverletzung etc.)
- [ ] Schule wird über die Krankmeldung und die Dauer Informiert

### User Story
https://github.com/SE-TINF22B2/G2-Schoolify/discussions/17
