### ISSUE TITLE
Klassenlehrer sieht alle Noten seiner Schüler (Frontend)

### ISSUE THREAD

**Issue by CodeRider101** [SE-TINF22B2/G2-Schoolify#103]
### Beschreibung
Noten der Schüler für die einzelnen Fächer anzeigen
Markierung der negativen Noten
Anzeige der Durchschnittsnoten der Schüler

### Task
 - [ ] Die Noten der Schüler werden korrekt angezeigt
 - [ ] Farbliche Gestaltung bei schlechten Notenspiegeln
 - [ ] Gesamtnoten der richtigen Person zuweisen

### Architektur 
- [Component Diagramm](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Component-Diagramm)

### Design
/

### User Story
[Als Klassenlehrer möchte ich alle Noten meiner Schüler sehen können, damit ich z.B. bei Defiziten mit dem Schüler oder dessen Eltern darüber sprechen kann und nichts verpasse #28](https://github.com/SE-TINF22B2/G2-Schoolify/discussions/28)

**Comment by CodeRider101** [comment]
Könnte man in Frontend/Backend Issue aufteilen. Gesamtnoten im Voraus berechnen, dann ist die Perfomance besser beim Zugriff auf die Seite, da es nicht zur Aufruf-Zeit berechnet werden muss.
