### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by CodeRider101** [SE-TINF22B2/G2-Schoolify#105]
### Beschreibung
Der Lehrer soll für jeden seiner Termine (Stunden) auf eine Übersichtsseite kommen können, in der aufgelistet ist, welche Schüler alle entschuldigt sind und welche anwesend sein sollen. Dadurch kann die Anwesenheit aller Schüler korrekt kontrolliert werden und unentschuldigtes Fehlen fällt schnell auf.

### Task
- [ ] Für jede Stunde kann ein Lehrer eine Liste seiner Schüler sehen
- [ ] entschuldigte Schüler werden farblich markiert
- [ ] anwesende Schüler kann man mit Häkchen bestätigen und mit x als unentschuldigt markieren

### Architektur 
/

### Design
/

### User Story
[Als Lehrer will ich mir anzeigen lassen, welche Schüler für meine Stunde entschuldigt sind, um die Anwesenheit korrekt kontrollieren zu können #26](https://github.com/SE-TINF22B2/G2-Schoolify/discussions/26)

**Comment by Schmarvinius** [comment]
Wusste nicht, dass es das schon gibt hab das mal aufgeteilt in Front und Backend 
#119 
#120
