### ISSUE TITLE
Elternsprechtag-Einladungen von Lehrern (groß und eher optional)

### ISSUE THREAD

**Issue by CodeRider101** [SE-TINF22B2/G2-Schoolify#107]
### Beschreibung
Wenn wichtige Termine (z.B. Elternsprechtag) eingetragen werden (für die es meist einen Elternbrief gibt) sollen Eltern eine Mail bekommen, um darüber benachrichtigt zu werden.
Lehrer können Elterngespräche im eigenen Kalender anlegen, den passenden Schüler auswählen und dessen Eltern werden per Email automatisch benachrichtigt.

### Task
- [ ] Elterngespräch Anlegefeld in der Lehreransicht für einen Schüler
- [ ] Valuelist mit verfügbaren Schülern (ggf. mit Suchbar)
- [ ] Elterngespräche können gecancelt werden -> Eltern werden wieder benachrichtigt
- [ ] (angenommende) Elterngespräche werden in den Kalender des jeweiligen Schülers eingetragen
------
- [ ] Admins können an die Eltern aller Schüler auf einmal eine Nachricht schicken (bspw. Schulschließung betrifft alle)
- [ ] Lehrer können an die Eltern ihrer Kursschüler eine Nachricht schicken
- [ ] Klassenlehrer können an die Eltern ihrer Klassenschüler eine Nachricht schicken (bspw. reminder für Geldüberweisung Ausflug)

### Architektur 
/

### Design 
/

### User Story
[Als Elternteil möchte ich für alle wichtigen Termine eine Benachrichtigung erhalten, um immer auf den neusten Stand meines Kindes zu sein. #24](https://github.com/SE-TINF22B2/G2-Schoolify/discussions/24)
