### ISSUE TITLE
(optional) Navigation zur Schule

### ISSUE THREAD

**Issue by CodeRider101** [SE-TINF22B2/G2-Schoolify#108]
### Beschreibung
Es soll eine Anbindung der Google Maps oder Deutsche Bahn API geben, die es Schülern ermöglicht einfach zu sehen wie sie heute am schnellsten oder generell zur Schule kommen. Am besten gibt es eine "kleine" Ansicht welche alles zusammenfasst und beim drauf klicken werden mehr Informationen angezeigt oder man wird zur Seite (Google Maps oder DB) weitergeleitet mit den angegeben Ziel und Startpunkt.

### Task
- [ ] API Verbindung zu Navigationsdienst herstellen
- [ ] Schuladresse als Zielort automatisch eingeben
- [ ] (einmalige) Einwilligungsfrage zur Standortermittlung des Schülers
- [ ] Standort des Schülers (wenn erlaubt) ermitteln und als Startort automatisch eingeben; sonst leer lassen 
- [ ] (optional: wenn kein Startort gefunden wurde oder Ermittlung nicht erlaubt ist, dann direkt autofocus auf Eingabefeld Startort)

### Architektur 
/

### Design
/

### User Story
[Als Schüler will ich das meine Schule automatisch als Ziel und meine Standort als Startpunkt ausgewählt wird für die Berechnung des Schulweges, falls ich das will, um Zeit zu sparen. #19](https://github.com/SE-TINF22B2/G2-Schoolify/discussions/19)
