### ISSUE TITLE
[Abwesenheitsverwaltung + Informationssysteme] Stunden bearbeiten und ausfallen lassen

### ISSUE THREAD

**Issue by CodeRider101** [SE-TINF22B2/G2-Schoolify#112]
### Beschreibung
Der Admin oder der Verwalter soll eine Nachricht bekommen falls ein Lehrer sich krankmeldet und die Möglichkeit haben die Stunde von einem anderen Lehrer vertreten zu lassen und eventuell den Raum zu ändern.
Dafür soll der Admin im Stundenplan am besten Vorschläge bekommen welcher Lehrer ein Fach bei der Klasse hat und dieses machen könnte (das Fach was der Lehrer eh in der Klasse hat) oder ein andere Lehrer der die Schüler beaufsichtigt und Aufgaben verteilt. Die Schüler sollen eine Mitteilung bekommen wenn sich etwas ändert.

### Task
- [ ] Admin kann die Fächer des kranken Lehrers einsehen und bearbeiten
- [ ] Admin kann den verantwortlichen Lehrer des Faches wechseln
- [ ] Bei einem Wechsel werden die Schüler und Eltern per E-Mail benachrichtigt
- [ ] Admin kann die Stunden per checkbox als "ausgefallen" markieren
- [ ] Bei einem Ausfall werden die Stunden grau in den Kalendern der jeweiligen Schüler angezeigt
- [ ] Bei einem Ausfall werden die Schüler und Eltern per E-Mail benachrichtigt

### Architektur 
/

### Design
/

### User Story
[Als Admin will ich die Möglichkeit haben ausgefallene Stunden vertreten zu lassen mit Lehren die können, um Stunden ausfälle zu verhindern und den Schüler mitzuteilen ob die Stunde ausfällt. #43](https://github.com/SE-TINF22B2/G2-Schoolify/discussions/43)
