### ISSUE TITLE
[Abwesenheitsverwaltung] Abwesenheits-Eintragung (Frontend)

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#116]
### Beschreibung
Es sollte eine eigene Seite geben auf der Schüler sich krankmelden können, anstatt bei der Schule anzurufen. Dabei sollen sie die Dauer und den Grund eintragen können.

### Task
- [ ] Dropdown Menu für Abwesenheitgrund
- [ ] Abwesenheitszeitraum Auswahl
- [ ] TextField für Mehr Informationen
- [ ] Submit Button (+ POST-Request)

### Architektur 
- [Component Diagramm](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Component-Diagramm)

### Design
- [Abwesenheit](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Weitere-Mockups#abwesenheit)

### User Story
- #17

**Comment by Schmarvinius** [comment]
Phase 0 bzw 1, da die Seite erstellt werden kann aber die richtigen Daten ja aus dem backend gezogen werden müssen
