### ISSUE TITLE
Token Generierung 

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#118]
### Beschreibung
JWT ist ein kompaktes Datenformat für sichere Informationstransfers in Webanwendungen, oft genutzt zur Authentifizierung durch die Übermittlung verschlüsselter Tokens zwischen Servern und Clients.

Hinweis: Bei jeder Request muss dieser Token mitgesendet werden sonst ist man nicht berechtigt. In diesem Token sind dann Log-In Daten gespeichert.

### Task
- [ ] Token bei Registrierung oder Log-In erstellen
- [ ] In der jeweiligen Request zurücksenden
- [ ] Token wird im Browser gespeichert
- [ ] Erstellung Middleware

### User Story
- #33

**Comment by Schmarvinius** [comment]
Sollte gemeinsam mit Sign In im Backend gemacht werden

**Comment by laralngn** [comment]
Issue Format passt nicht zu dem Format anderer Issues mit Feature-Anfrage etc..
Außerdem wird in der Beschreibung eher das Konzept von JWT und nicht das Issue beschrieben.
