### ISSUE TITLE
(optional) Automatisch generierter Stundenplan

### ISSUE THREAD

**Issue by Schmarvinius** [SE-TINF22B2/G2-Schoolify#121]
### Beschreibung
Der Admin soll eingeben können welche Klasse welche Stunden und Räume braucht und welche Lehrer welche Stunden macht und nach diesen Kriterien Stundenpläne erzeugen.

### Task
- [ ] Stundenpläne werden erstellt und falls möglich alle Stunden einer Klasse erfüllt
- [ ] Aufgaben lasst wird verteilt auf die Lehrer
- [ ] Keine Stunden nach 17 Uhr
- [ ] Keine Leerstunden falls möglich
- [ ] Klassenräume werden nach Fächern zu gewiesen falls nötig (Computerraum / Chemieraum etc.)

### User Story
- #20

**Comment by two-Gee** [comment]
Issue schließen?
