### ISSUE TITLE
Architektur Backend erstellen und initialisieren

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#165]
## Description 
Es sollen die ersten Schritte getan werden, dass in den folgenden Wochen, dann auf einer gemeinsamen Basis programmiert werden kann. Die Task enthalten nur ganz wage Informationen und sollen von dem 2er Team weiterentwickelt werden und dann aufgeschrieben werden. 

## Task

- [x] Ordner Struktur
- [x] Erste Architektur für die Klassen 
- [x] ERM Definition
- [x] Verbindung zur Datenbank
- [x] Erste Mockdaten erstellen

## Issue 
Dieses Issue ist ein Teil des Projekt Architektur Issue #166
