### ISSUE TITLE
Architektur des Projektes

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#166]
# Beschreibung 
Die Idee ist das jeweils 2 Teams aus 2 Leuten sich um die ersten schritte im Projekt für Backend und Frontend initialisieren.
Es sind jetzt noch keine genauen Angaben gegeben diese sollen dann von den Teams überlegt werden.

# Task 

- [x] Das Fronteend soll bereit für die Issues sein und initialisiert sein 
- [x] Das Backend soll bereit für die Issues sein und initialisiert sein 
- [x] Änderungen in das Handbuch eintragen 

#Sub-Issues
- #164
- #165
