### ISSUE TITLE
Leistungskontrolle (Backend )

### ISSUE THREAD

**Issue by CodeRider101** [SE-TINF22B2/G2-Schoolify#207]
### Beschreibung
Es soll eine Übersicht aller korrigierter und nicht korrigierter Tests geben. Bei nicht korrigierten Tests soll es eine Liste zum Bewerten aller Schüler geben.

### Task
- [x] GET-Request - Auslesen aller Tests
- [x] GET-Request - Auslesen aller korrigierten Tests
- [x] GET-Request - Auslesen aller nicht korrigierten Tests
