### ISSUE TITLE
[SE] Anforderungen SE

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#219]
# Beschreibung
In den Anforderungen sind ein paar Unebenheiten. Diese sollen verbessert werden.
- Im [Big Picture](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Big-Picture#%C3%BCbersicht) sind wesentliche Funktionsblöcke als Übersicht aufgelistet. Diese Struktur soll auch für die detaillierte Ebene ([Funktionale Anforderungen](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Funktionale-Anforderungen)) verwendet werden. 
=> Dort sind aktuell "Wetterdienst" und "Leistungsübersicht" neu (fehlen im Big Picture); die "Abwesenheitsverwaltung" fehlt aber (steht im Big Picture)
- [Ziele](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Big-Picture#ziele): Die Punkte 1,2 und 4 sind Ziele. Nr. 3 (Google Maps) ist eher eine weitere Funktionalität, das gehört woanders hin.
- [Wichtige Merkmale](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Big-Picture#wichtige-merkmale): Hier passen 1,2 und 4 gut in die Liste (wenn man 4 als Erläuterung betrachtet, dass das System eben nicht nur passiv Informationen zur Verfügung stellt, sondern auch aktiv den Anwender benachrichtigen soll). Nr. 3 ist eher ein Funktionsblock.
- **Rollen**: Aus den [Funktionale Anforderungen](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Funktionale-Anforderungen) gehen die Rollen **Lehrer**, **Schüler** und **Mensapersonal** hervor. Diese Rollen sollen explitizt beschrieben werden, um u.a. Inkonsistenzen zu vermeiden (bei der "Rollenbasierten Zugriffskontrolle" werden nämlich die Rollen Lehrer/Schüler/Admin genannt)

# Tasks
- [x] Struktur aus Big Picture Übersicht in den funktionalen Anforderungen übernehmen
- [x] "Wetterdienst" und "Leistungsübersicht" im Big Picture **hinzufügen** 
- [x] "Abwesenheitsverwaltung" in den funktionalen Anforderungen hinzufügen
- [x] Ziel 3 (Google Maps) bei Funktionalitäten entfernen
- [x] Rollen explizit beschreiben => funktionale Anforderungen dementsprechend auch anpassen
- [x] Merkmal 3 als Funktionsblock definieren, nicht in wichtigen Merkmalen
- [x] ggf. Merkmal 4 als genauer als Erläuterung, dass das System nicht nur passiv Informationen zur Verfügung stellt, sondern auch aktiv den Anwender benachrichtigen soll, formulieren

**Comment by laralngn** [comment]
Rollen und Funktionalitäten diskutieren

**Comment by laralngn** [comment]
Wohin mit Merkmal 3?

**Comment by laralngn** [comment]
Wohin mit Ziel 3 als Funktionalität?

**Comment by laralngn** [comment]
Öffnungszeiten und Telefonnummern auch in Funktionalen Anforderungen erwähnen?

**Comment by laralngn** [comment]
Wo Rollen beschreiben?

**Comment by Kronprinz03** [comment]
Wenn die fragen nicht beantwortet werden kannst du die fragen hier #228 eintragen, dann reden wir das nächste Meeting drüber

**Comment by Kronprinz03** [comment]
> Wohin mit Ziel 3 (Wetter API) als Funktionalität?

Ja Google Maps ist ja kein Ziel mehr dachte nur ersetzten

**Comment by laralngn** [comment]
> > Wohin mit Ziel 3 (Wetter API) als Funktionalität?
> 
> Ja Google Maps ist ja kein Ziel mehr dachte nur ersetzten

Also gilt auch die neue API nicht mehr als Ziel und wird nur beim Informationssystem gelistet?
