### ISSUE TITLE
[SE] User Stories überarbeiten

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#220]
# Beschreibung
Bisher steht die gesamte User Story im Title, dadurch ist es sehr unübersichtlich diese in der Übersicht anzuzeigen.
Außerdem fehlt der Nutzen (also was das Feature bringt) in manchen User Stories und die Beschreibung ist nicht ausreichend. Zudem wird eine generische Rolle "User" genutzt, diese sollte durch eine Auflistung aller betroffenen Rollen ersetzt werden.

### Umsetzung:
Im Titel soll nur noch eine kurze Beschreibung/Einordnung stehen.
Die gesamte User Story soll erst sichtbar sein, wenn man auf die User Story klickt. 
Es soll zudem geprüft werden ob der Nutzen in der User Story vorhanden ist, falls nicht soll diese ergänzt werden.
Die Beschreibung weiterhin soll überprüft werden ob ggf. detaillierter formuliert werden.
Als letztes soll die generische "User" Rolle entfernt werde.

# Tasks
- [x] User Story aus Titel entfernen und in Kommentar hinzufügen 
- [x] Kurze Beschreibung in Titel hinzufügen
- [x] Nutzen in User Story prüfen und ggf. hinzufügen
- [x] Ausführliche Beschreibung der User Story prüfen und ggf. verbessern oder hinzufügen
- [x] "User" Rolle ersetzen

**Comment by laralngn** [comment]
| Person | Zeitaufwand |
| @two-Gee | 1.5h |
|@laralngn | 1.5h |
