### ISSUE TITLE
[SE] Projekthandbuch

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#221]
# Beschreibung
Das Projekthandbuch soll angepasst und erweitert werden, um die Aspekte des Projektmanagements zu dokumentieren. Dazu gehören:
1. **Projektorganisation** (u.a. das Team und die zugehörige Rollen)
2. Wie ist die **Zusammenarbeit** organisiert?
3. Welche **PM-unterstützenden Werkzeuge** nutzen wir in welcher Form _(z.B. GitHub-Projects, Discussions, Issues … ggf. weitere)_? 

# Tasks
- [x] Projektorganisation (Team und Rollen) in Projekthandbuch verschieben
- [x] Zusammenarbeit genauer beschreiben
    - [x] (Regelmäßige) Termine
    - [x] Statusberichte
    - [x] Prozesse für Change Requests/Neue Anforderungen o.ä.
    - [x] Projektplanung und -controlling (dazu gehört auch das Schätzen und Erfassen von Aufwänden)
- [ ] Nutzung von PM-unterstützenden Werkzeugen beschreiben
    - [x] In welcher Form nutzen wir welche Werkzeuge?
    - [x] z.B. die Bedeutung und Nutzung der Labels in den Issues spezifizieren
    - [x] Prozesse der Software-Entwicklung
    - [x] Wie wird Git zur Versions- und Konfigurationsverwaltung eingesetzt?
    - [x] Wie sieht der Testprozess aus?
    - [x] CI/CD-Workflow
    - [x] Richtlinien für die Implementierung (Code Style-Guides), dto. für die Dokumentation

**Comment by laralngn** [comment]
Neuere Version von Issue #74

**Comment by laralngn** [comment]
Evtl. in Subissues aufteilen

**Comment by CodeRider101** [comment]
name | Aufwand
-- | --
@tilwbr | 0.5
