### ISSUE TITLE
[SE] Datenmodell und Architektur

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#223]
# Beschreibung:
Auf Grundlage des Datenmodells soll ein Entwurf der Anwendungsarchitektur erstellt werden. 
Aus der Technologiebeschreibung (Frontend/Backend) ergibt sich schon, dass es sich um ein **verteiltes System mit einer 3-stufigen Client/Server-Architektur** handeln wird. Das muss noch expliziter gemacht werden.
Damit können für das Frontend und das Backend jeweils die wesentlichen Komponenten definiert werden (für das Backend bildet das Datenmodell bereits eine gute Grundlage).

# Tasks
- [x] Architektur Entwurf erstellen
- [x] Wesentliche Komponenten fürs Frontend definieren
- [x] Wesentliche Komponenten fürs Backend definieren

**Comment by laralngn** [comment]
#40

**Comment by Kronprinz03** [comment]
Sollte mit dem neuen Komponenten Diagram erledigt sein
