### ISSUE TITLE
[SE] Weitere Ausarbeitung Architektur

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#250]
### Beschreibung 
Das Komponenten Diagramm  soll nun weiter ins Detail ausgearbeitet werden. 

### Task
- [x] API Aufteilung auf die "großen" Komponenten
- [x] Für den Projektscope entwickeln 
- [x] AT Komponenten in der Architektur kennzeichnen

**Comment by two-Gee** [comment]
NewsController ändern zu NewsAbrufen
