### ISSUE TITLE
Authentification Registration

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#92]
### Beschreibung
Als Admin soll ich die Möglichkeit haben neue Accounts anzulegen. Die Authentifizierung über die Rolle soll im Frontend nur dadurch geregelt werden, dass nur der Admin die Möglichkeit hat (z.B. Extra Button). Die Authentifizierung ob dieser Account über die Berechtigung verfügt soll im Backend stattfinden.

### Task
- [ ] Admin soll sich neue Account erstellen können
- [ ] Den Account können von dem Admin funktionierende Rollen gegeben werden
- [ ] Schüler/Lehrer können sich mit diesen anmelden
- [ ] Visuelle Hilfe bei Falschen angaben (z.B Dopplung)
- [ ] Edge-Cases beachten (z.B. Sonderzeichen oder Fehler)

### Architektur 
[Component Diagram](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Component-Diagramm)

### Design
Fehlt

### User Story
[Account erstellen](https://github.com/SE-TINF22B2/G2-Schoolify/discussions/31)

**Comment by saisreesatyassss** [comment]
i am trying to slove but getting Internal Server Error

**Comment by Schmarvinius** [comment]
Phase 0 bzw 1, da die Seite erstellt werden kann aber die richtigen Daten ja aus dem backend gezogen werden müssen

**Comment by two-Gee** [comment]
Dopplung mit #94. Kann geschlossen werden?
