### ISSUE TITLE
Authentification Registration

### ISSUE THREAD

**Issue by Kronprinz03** [SE-TINF22B2/G2-Schoolify#94]
### Beschreibung
Als Admin soll ich die Möglichkeit haben neue Accounts anzulegen. Das Backend empfängt die Daten für den neu zu erstellenden Account und den Account des Admin und erstellt daraus neue Accounts mit den angegebenen Rollen auf der Datenbank

### Task
- [x] Neue User werden auf der Datenbank erstellt
- [x] Edgecase-behandlung z.B. Duplikate 
- [x] Authentifizierung der Berechtigungen des Account der die User erstellen soll

### Architektur 
- [Component Diagram](https://github.com/SE-TINF22B2/G2-Schoolify/wiki/Component-Diagramm)

### User Story
- [Account erstellen](https://github.com/SE-TINF22B2/G2-Schoolify/discussions/31)
